CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    short_path VARCHAR(7) UNIQUE NOT NULL,
    url VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    clicks INTEGER DEFAULT 0
);
